- build fix for systems that dont have docbook.xsl

diff --git a/doc/Makefile.am b/doc/Makefile.am
--- a/doc/Makefile.am
+++ b/doc/Makefile.am
@@ -4,6 +4,13 @@ EXTRA_DIST = openct.xml openct.xsl openct.html openct.css
 noinst_DATA = openct.html
 
 %.html: %.xml
-	        xsltproc -o $@ openct.xsl $< 
-		tidy -im -utf8 -xml $@ || true
+	@if [ -f /usr/share/sgml/docbook/stylesheet/xsl/nwalsh/xhtml/docbook.xsl ]; then \
+	        echo xsltproc -o $@ openct.xsl $<; \
+	        xsltproc -o $@ openct.xsl $<; \
+		echo tidy -im -utf8 -xml $@; \
+		tidy -im -utf8 -xml $@ || true; \
+	else \
+		echo "docbook.xsl not installed, cannot generate $@ docs" >&2; \
+		touch $@; \
+	fi
 
